"""The reply is generated by the server, not by the request watching it.

Closing a tab, locking a phone or losing wifi used to end the generation
itself, because the generator lived exactly as long as the connection did.
Evermind is most often used from a phone against a machine somewhere else,
which is the situation where that happens constantly.
"""

import asyncio

import pytest

from app.models.schemas import ChatRequest
from app.services import turns
from tests.test_chat import setup_conversation
from tests.test_streaming_persistence import UnhurriedProvider


@pytest.fixture()
def unhurried(monkeypatch):
    monkeypatch.setattr("app.services.chat_service.get_provider", UnhurriedProvider)
    monkeypatch.setattr("app.services.memory_service.get_provider", UnhurriedProvider)


@pytest.fixture(autouse=True)
def empty_registry(monkeypatch):
    monkeypatch.setattr(turns, "_running", {})


async def _messages(client, convo_id):
    return (await client.get(f"/api/conversations/{convo_id}")).json()["messages"]


async def test_the_reply_finishes_after_the_reader_walks_away(client, unhurried):
    convo = await setup_conversation(client)
    turn = await turns.start(ChatRequest(
        conversation_id=convo["id"], mode="send", content="Reste avec moi"))

    # A reader arrives, takes a few events and leaves — a tab being closed.
    reader = turns.follow(turn)
    for _ in range(3):
        await reader.asend(None)
    await reader.aclose()

    await asyncio.wait_for(turn.finished.wait(), timeout=15)

    reply = (await _messages(client, convo["id"]))[-1]
    assert reply["role"] == "assistant"
    assert reply["content"].strip().endswith("mot11"), (
        f"the generation stopped when the reader did: {reply['content']!r}"
    )
    assert "streaming" not in reply["meta"], "a reply that ran to the end is not unfinished"


async def test_coming_back_attaches_to_the_reply_being_written(client, unhurried):
    convo = await setup_conversation(client)
    turn = await turns.start(ChatRequest(
        conversation_id=convo["id"], mode="send", content="Continue"))

    first = turns.follow(turn)
    await first.asend(None)
    await first.aclose()

    # The phone comes back mid-reply.
    assert turns.running_for(convo["id"]) is turn
    seen = [chunk async for chunk in turns.follow(turn)]
    assert any('"delta"' in c for c in seen), "attaching gave nothing of the reply"
    assert any('"done"' in c for c in seen), "attaching did not carry through to the end"


async def test_a_second_request_joins_rather_than_starting_another(client, unhurried):
    """A phone that reconnects and asks again must not set a second reply
    generating alongside the first."""
    convo = await setup_conversation(client)
    # The card has a greeting, so the conversation already opens on one reply.
    before = len([m for m in await _messages(client, convo["id"]) if m["role"] == "assistant"])

    request = ChatRequest(conversation_id=convo["id"], mode="send", content="Une fois")
    first = await turns.start(request)
    second = await turns.start(request)
    assert first is second

    await asyncio.wait_for(first.finished.wait(), timeout=15)
    after = len([m for m in await _messages(client, convo["id"]) if m["role"] == "assistant"])
    assert after - before == 1, f"one message produced {after - before} replies"


async def test_stopping_is_asked_for_and_takes_effect(client, unhurried):
    convo = await setup_conversation(client)
    turn = await turns.start(ChatRequest(
        conversation_id=convo["id"], mode="send", content="Arrete-toi"))

    reader = turns.follow(turn)
    for _ in range(3):
        await reader.asend(None)
    assert await turns.stop(convo["id"]) is True
    await reader.aclose()

    await asyncio.wait_for(turn.finished.wait(), timeout=15)
    reply = (await _messages(client, convo["id"]))[-1]
    assert not reply["content"].strip().endswith("mot11"), (
        "asked to stop and it ran to the end anyway"
    )
    assert reply["content"].startswith("mot0"), "what had arrived should still be kept"


async def test_a_finished_turn_is_not_offered_as_running(client, unhurried):
    convo = await setup_conversation(client)
    turn = await turns.start(ChatRequest(
        conversation_id=convo["id"], mode="send", content="Fini"))
    await asyncio.wait_for(turn.finished.wait(), timeout=15)
    assert turns.running_for(convo["id"]) is None, (
        "a page would attach to a stream with nothing left to say"
    )


async def test_a_regeneration_also_finishes_after_its_reader_leaves(client, unhurried):
    """Reported from a phone, and the mode matters: regenerating replaces the
    last reply rather than adding one, and the reader leaving mid-way is the
    same screen going off."""
    convo = await setup_conversation(client)
    await client.post("/api/chat", json={
        "conversation_id": convo["id"], "mode": "send", "content": "Dis quelque chose"})
    before = await _messages(client, convo["id"])
    target = before[-1]
    assert target["role"] == "assistant"

    turn = await turns.start(ChatRequest(conversation_id=convo["id"], mode="regenerate"))
    reader = turns.follow(turn)
    for _ in range(3):
        await reader.asend(None)
    await reader.aclose()

    await asyncio.wait_for(turn.finished.wait(), timeout=15)

    after = await _messages(client, convo["id"])
    assert len(after) == len(before), "a reply was added rather than replaced"
    replaced = after[-1]
    assert replaced["id"] == target["id"]
    assert len(replaced["variants"]) == 2, (
        f"the regeneration stopped when its reader did: {replaced['variants']}"
    )
    assert replaced["variants"][-1].strip().endswith("mot11"), (
        "the replacement was cut short"
    )
