"""Turns that belong to the server rather than to the request that asked for one.

A reply used to be generated by the HTTP request streaming it: the generator
lived exactly as long as the connection did, so closing a tab, locking a phone
or losing wifi ended the generation itself. What had already arrived was kept —
the reply is written as it streams — but the rest was never written at all, and
coming back meant sending the message again.

The turn runs here instead, on a task of its own with its own database
connection, and a request is only ever a reader of it. A reader going away
detaches; the turn carries on to the end and saves. Coming back attaches to it
if it is still running, and finds the finished reply if it is not.
"""

import asyncio
from dataclasses import dataclass, field

from ..db import _connect
from ..models.schemas import ChatRequest
from . import chat_service

# How long a finished turn stays around after its last event. Long enough for
# someone whose phone woke up to attach and be handed the ending; short enough
# that a day of chatting does not accumulate transcripts in memory.
_KEEP_FINISHED_SECONDS = 120


@dataclass
class Turn:
    conversation_id: str
    # What kind of turn this is. A page attaching to one in progress needs it:
    # a regeneration replaces a reply that is already on screen, and without
    # knowing that, the page shows both the old one and the new one arriving
    # underneath as though a second reply were being added.
    mode: str = "send"
    # Every event this turn has emitted, so a reader arriving late gets the
    # whole reply rather than the tail of it.
    events: list[str] = field(default_factory=list)
    readers: set[asyncio.Queue] = field(default_factory=set)
    finished: asyncio.Event = field(default_factory=asyncio.Event)
    stopped: bool = False
    task: asyncio.Task | None = None

    def emit(self, chunk: str) -> None:
        self.events.append(chunk)
        for queue in self.readers:
            queue.put_nowait(chunk)


_running: dict[str, Turn] = {}
_lock = asyncio.Lock()


def running_for(conversation_id: str) -> Turn | None:
    """A turn still being written, or None. A finished one is not offered: its
    reply is in the conversation by then, which is where a page will look."""
    turn = _running.get(conversation_id)
    return turn if turn and not turn.finished.is_set() else None


async def _run(turn: Turn, request: ChatRequest) -> None:
    db = await _connect()
    try:
        async for chunk in chat_service.stream_turn(db, request):
            turn.emit(chunk)
            if turn.stopped:
                # Asked to stop, rather than merely unwatched. Closing the
                # generator here is what ends the provider request too.
                break
    except asyncio.CancelledError:
        raise
    except Exception as exc:  # noqa: BLE001 - a crash here must still release readers
        turn.emit(chat_service._sse({"type": "error", "message": str(exc)}))
    finally:
        await db.close()
        turn.finished.set()
        for queue in turn.readers:
            queue.put_nowait(None)
        asyncio.get_running_loop().call_later(
            _KEEP_FINISHED_SECONDS, _running.pop, turn.conversation_id, None)


async def start(request: ChatRequest) -> Turn:
    """Begin a turn, or hand back the one already under way.

    Two requests for the same conversation are the same turn: a phone that
    reconnects and asks again must not set a second reply generating alongside
    the first.
    """
    async with _lock:
        existing = running_for(request.conversation_id)
        if existing:
            return existing
        turn = Turn(conversation_id=request.conversation_id, mode=request.mode)
        _running[request.conversation_id] = turn
        turn.task = asyncio.create_task(_run(turn, request))
        return turn


async def stop(conversation_id: str) -> bool:
    """Stop is a decision, and it now has to be said out loud. While the request
    owned the generation, hanging up was how you stopped it; a turn that
    survives being unwatched cannot read anything into a reader leaving."""
    turn = running_for(conversation_id)
    if not turn:
        return False
    turn.stopped = True
    return True


async def follow(turn: Turn):
    """Everything the turn has said so far, then the rest as it arrives."""
    queue: asyncio.Queue = asyncio.Queue()
    # Snapshot and subscribe with no await between them, so the two cannot
    # interleave: nothing emitted is missed, and nothing is handed over twice.
    backlog = list(turn.events)
    turn.readers.add(queue)
    try:
        for chunk in backlog:
            yield chunk
        if turn.finished.is_set():
            return
        while True:
            chunk = await queue.get()
            if chunk is None:
                return
            yield chunk
    finally:
        turn.readers.discard(queue)
