import { expect, test } from "@playwright/test";
import { API } from "../playwright.config";
import { conversationWithReply } from "./fixtures";

/**
 * Evermind is most often used from a phone against a machine somewhere else,
 * where a tab closing or a screen locking is constant. The reply used to be
 * generated by the request watching it, so all of that ended the generation.
 */
test("the reply keeps being written after the page goes away", async ({ browser, request }) => {
  const convo = await conversationWithReply(request);
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto(`/chat/${convo.id}`);

  await page.locator("textarea").first().fill("Continue, je pars.");
  await page.locator('button[title="Send"]').click();
  await expect(page.locator('button[title="Stop generation"]')).toBeVisible();

  // The phone goes to sleep.
  await context.close();

  // The server was asked, not the page, so the turn is still going.
  await expect.poll(async () =>
    (await (await request.get(`${API}/api/conversations/${convo.id}/turn`)).json()).running,
    { timeout: 5_000 }).toBe(true);

  await expect.poll(async () =>
    (await (await request.get(`${API}/api/conversations/${convo.id}/turn`)).json()).running,
    { timeout: 30_000 }).toBe(false);

  const messages = (await (await request.get(`${API}/api/conversations/${convo.id}`)).json()).messages;
  const reply = messages.at(-1);
  expect(reply.role).toBe("assistant");
  expect(reply.meta.streaming, "left unfinished, so the generation died with the page").toBeUndefined();
  expect(reply.content.length).toBeGreaterThan(40);
});

test("coming back shows the reply still arriving", async ({ browser, request }) => {
  const convo = await conversationWithReply(request);
  const first = await browser.newContext();
  const page = await first.newPage();
  await page.goto(`/chat/${convo.id}`);
  await page.locator("textarea").first().fill("Ecris longuement.");
  await page.locator('button[title="Send"]').click();
  await expect(page.locator('button[title="Stop generation"]')).toBeVisible();
  await first.close();

  // Somebody opens the conversation again while it is still being written.
  const second = await browser.newContext();
  const back = await second.newPage();
  await back.goto(`/chat/${convo.id}`);
  await expect(back.locator('button[title="Stop generation"]'),
    "the conversation looked finished while a reply was still being written").toBeVisible();
  await second.close();
});
